version: '3'
services:
  nestjs-app:
    build:
      context: ./microservices/movies-service/src # O caminho para o diretório do seu aplicativo Nest.js
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapeie a porta do contêiner para a porta do host
    depends_on:
      - mongo

  mongo:
    build:
      context: ./microservices/movies-service/src # O caminho para o diretório do Dockerfile do MongoDB
      dockerfile: Dockerfile
    ports:
      - "27017:27017" # Mapeie a porta do contêiner para a porta do host
